Repository Space2Study-Project/Space2Study-FrontEnd, pull requests merged in 2023-11, with the labels that each got.

#87 fix bag#59
  src/containers/guest-home-page/google-button/GoogleButton.jsx
  src/containers/guest-home-page/google-button/GoogleButton.styles.js
  src/containers/guest-home-page/google-login/GoogleLogin.jsx
  src/containers/guest-home-page/google-login/GoogleLogin.styles.js
  src/containers/guest-home-page/login-form/LoginForm.styles.js
Labels: bug

#88 [Password reset] The “Email” input field is overlapped by description text.#58
  src/containers/guest-home-page/forgot-password/ForgotPassword.styles.js
Labels: bug

#95 [Home page] The item descriptions are bold in the home page “How it works” block#63
  src/components/title-with-description/TitleWithDescription.styles.js
Labels: bug, FrontEnd part, Home page

#93 Tutor sign up pop up #66
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/guest-home-page/signup-form/SignupForm.jsx
Labels: bug

#96 fix bug #67 / fix guest-home-page.json
  src/constants/translations/en/guest-home-page.json
Labels: bug

#108 Tests #97 loader
  tests/unit/components/loader/Loader.spec.jsx
Labels: FrontEnd part, Unit test

#105 bugFix#104
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/containers/guest-home-page/signup-form/SignupForm.jsx
Labels: bug

#94 added function for closing popup modals
  src/components/popup-dialog/PopupDialog.jsx
Labels: bug, FrontEnd part

#114 added tests
  tests/unit/components/input-with-icon/InputWithIcon.spec.jsx
Labels: FrontEnd part, Unit test

#113 change when press “Space2Study” logo buttom page scrooll to the top
  src/components/scroll-to-top-button/ScrollToTopButton.jsx
  src/containers/app-content/AppContent.jsx
  src/containers/layout/app-header/AppHeader.jsx
  src/containers/layout/app-main/AppMain.jsx
  src/containers/layout/navbar/NavBar.jsx
  src/services/scroll-to-top.js
  tests/unit/components/layout/AppMain.spec.jsx
Labels: bug, FrontEnd part
